config/routes.rb
Rails.application.routes.draw do

  resources :orders
  get 'ships/getstates' => 'ships#getstates'
  

  

  controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
  end

  resources :ships
  resources :users
  resources :states
  resources :countries
  resources :line_items
  resources :carts
  root 'pages#index', as: 'pages_index'

  get 'pages/about'

  get 'pages/contact'

  resources :products
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
end

def total_price

    line_items.to_a.sum{ |item| item.total_price}
    
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :states, dependent: :destroy

    validates :name, presence: true, uniqueness: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product, optional: true 
  belongs_to :cart
  belongs_to :order, optional: true

  def total_price
    
    product.price * quantity

  end



end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :ship
  accepts_nested_attributes_for :ship, allow_destroy: true
  has_many :line_items

  enum payment: {
    "unpaid" => 0,
    "paid" => 1
  }

  enum order_status: {
    "Unsuccess" => 0,
    "In Progress" => 1,
    "Success" => 2
  }

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :line_items
end

app/models/ship.rb
class Ship < ApplicationRecord
  belongs_to :country
  belongs_to :state
  has_one :order
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true, uniqueness: true

  has_many :orders

  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'front', only: [:new, :create, :edit,:update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to pages_index_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :username, :password, :password_confirmation, :email, :add1, :phone, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <%= form_with(model: user, local: true) do |form| %>
    <div class="p-3 p-lg-5 border">
      <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <div class="form-group row">
          <div class="col-md-6">
            <%= form.label :fname, class: "text-black" %>
          </div>
          <div class="col-md-6">
            <%= form.text_field :fname, id: :user_fname, class:"form-control" %>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="form-group row">
          <div class="col-md-6">
            <%= form.label :lname, class: "text-black" %>
          </div>
          <div class="col-md-6">
            <%= form.text_field :lname, id: :user_lname, class:"form-control" %>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="form-group row">
          <div class="col-md-6">
            <%= form.label :username, class: "text-black" %>
          </div>
          <div class="col-md-6">
            <%= form.text_field :username, id: :user_username, class:"form-control" %>
          </div>
        </div>
      </div>

        <div class="field">
        <div class="form-group row">
          <div class="col-md-6">
            <%= form.label :password, class: "text-black" %>
          </div>
          <div class="col-md-6">
            <%= form.password_field :password, id: :user_password, class:"form-control" %>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="form-group row">
          <div class="col-md-6">
            <%= form.label :password_confirmation, class: "text-black" %>
          </div>
          <div class="col-md-6">
            <%= form.password_field :password_confirmation, id: :user_password_confirmation, class:"form-control" %>
          </div>
        </div>
      </div>
     
     <div class="field">
        <div class="form-group row">
          <div class="col-md-6">
            <%= form.label :email, class: "text-black" %>
          </div>
          <div class="col-md-6">
            <%= form.text_field :email, id: :user_email, class:"form-control" %>
          </div>
        </div>
      </div>


      

     

      <div class="field">
        <div class="form-group row">
          <div class="col-md-6">
            <%= form.label :phone, class: "text-black" %>
          </div>
          <div class="col-md-6">
            <%= form.text_field :phone, id: :user_phone, class:"form-control" %>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="form-group row">
          <div class="col-md-6">
            <%= form.label :add1, class: "text-black" %>
          </div>
          <div class="col-md-6">
            <%= form.text_area :add1, id: :user_add1, cols: "30", rows: "5", class:"form-control" %>
          </div>
        </div>
      </div>
      
      <div class="field">
        <div class="form-group row">
          <div class="col-md-6">
            <%= form.label :active, class: "text-black" %>
          </div>
          <div class="col-md-6">
            <%= form.check_box :active, id: :user_active %>
          </div>
        </div>
      </div>
     

      <div class="actions">
        <div class="form-group row">
          <div class="col-lg-6 offset-3">
            <%= form.submit 'Register', :class =>"btn btn-primary btn-lg btn-block" %>
          </div>        
        </div>
      </div>

    </div>
  <% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Username</th>
      <th>Email</th>
      <th>Add1</th>
      <th>Phone</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.add1 %></td>
        <td><%= user.phone %></td>
        <td><%= user.active %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="custom-border-bottom py-3">
  <div class="container">
    <div class="row">
      <div class="col-md-12 mb-0"><a href="index.html">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Register</strong></div>
    </div>
  </div>
</div>

<div class="site-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="h3 mb-3 text-black">Get In Touch</h2>
      </div>
    <div class="col-md-7">
      <%= render 'form', user: @user %>
    </div>
  </div>
  <%= link_to 'click to Login here', login_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Add1:</strong>
  <%= @user.add1 %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Active:</strong>
  <%= @user.active %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>